---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: template
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-silverblue
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - brave-origin
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - gnome-software
        - gnome-tour
        - htop
        - nvtop

  - type: script
    snippets:
  	- "rm /etc/yum.repos.d/*"
    
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - io.github.kolunmi.Bazaar
      - scope: user
